### ISSUE TITLE
v2.0.0 prefers '.d.ts' files to '.js' files when both exist.

### ISSUE THREAD

**Issue by jgerigmeyer** [alexgorbatchev/eslint-import-resolver-typescript#33]
In v2.0.0, it seems that the change from:

```js
  const extensions = Object.keys(require.extensions).concat(
    '.ts',
    '.tsx',
    '.d.ts',
  );
```

to:

```js
const extensions = ['.ts', '.tsx', '.d.ts'].concat(
  // eslint-disable-next-line node/no-deprecated-api
  Object.keys(require.extensions),
  '.jsx',
)
```

...means that if a node module is imported and contains both `.js` and `.d.ts` files, the `.d.ts` file is now resolved instead of the `.js` one. This results in `import/default` errors, e.g.:

```js
import React from 'react';
```

```
error: No default export found in module (import/default)
```

Maybe I'm missing something obvious?

**Comment by JounQin** [comment]
Yes, it's just working as expected.
See https://github.com/alexgorbatchev/eslint-import-resolver-typescript/issues/31#issuecomment-539751607

**Comment by alexgorbatchev** [comment]
@JounQin would it make sense to document this behavior somewhere in README?

**Comment by joaovieira** [comment]
@JounQin Sorry, don't know what you mean by "it's working as expected". Both here and [here](https://github.com/alexgorbatchev/eslint-import-resolver-typescript/issues/31#issuecomment-539922999). I'm having issues with lodash as well, just as in https://github.com/alexgorbatchev/eslint-import-resolver-typescript/issues/31.

<img width="544" alt="Screen Shot 2019-10-29 at 16 39 18" src="https://user-images.githubusercontent.com/474603/67788930-1149ba80-fa6b-11e9-87c7-a93df5b35800.png">


In all of these scenarios, there is a default export that always used to work:

```ts
// node_modules/dataloader/index.d.ts
declare class DataLoader {}
export = DataLoader;
```

```ts
// node_modules/@types/lodash/snakeCase.d.ts
import { snakeCase } from "./index";
export = snakeCase;
```

So it's not working as _we're_ expecting.

**Comment by JounQin** [comment]
It's not ES Module `default export`, it's `commonjs`, that why the `eslint-plugin-import` complains about `no default export`.

**Comment by JounQin** [comment]
And you should issue to `eslint-plugin-import` for help supporting that instead.

**Comment by joaovieira** [comment]
With `esModuleInterop`.

It used to worked well (apart from https://github.com/benmosher/eslint-plugin-import/issues/1282#issuecomment-525776293), but v2.0.0 started to break normal usage as mentioned. On top of those already mentioned, `import/order` also started to raise:

<img width="686" alt="Screen Shot 2019-10-29 at 17 28 05" src="https://user-images.githubusercontent.com/474603/67805112-40baf000-fa88-11e9-82b5-49883107f085.png">

express: external types in `@types/express` - seen as "internal"
http-status-codes: own types - seen as "external"

I'm not that well versed in `eslint-plugin-import` and/or `eslint-import-resolver-typescript` to understand what is going on - or even where the boundaries are. So can't say yet where the problem is. But, as a consumer, it's not working as expected.

Regarding disabling the rules: https://github.com/typescript-eslint/typescript-eslint/issues/154#issuecomment-547567531

**Comment by JounQin** [comment]
`esModuleInterop` is TypeScript spec and `eslint-plugin-import` doesn't understand standard it, that's why I told you to issue to it instead.

**Comment by joaovieira** [comment]
Ok. For the `import/order`, I've raised https://github.com/benmosher/eslint-plugin-import/issues/1525 and fixed in https://github.com/benmosher/eslint-plugin-import/pull/1526.

For the `import/default`, where do you think the problem would be? In the parser or the import plugin?

In `1.1.1` reading from the JS source (`lodash/snakeCase.js`) works fine:

```js
var snakeCase = createCompounder(function(result, word, index) {
  return result + (index ? '_' : '') + word.toLowerCase();
});

module.exports = snakeCase;
```

In `v2.0.0` using the TS export syntax in the type definition (`@types/lodash/snakeCase.d.ts`):

```ts
import { snakeCase } from "./index";
export = snakeCase;
```

Does not work.

**Comment by JounQin** [comment]
I've told you the type definition is commonjs format and `eslint-plugin-import` doesn't treat it as an ES Module then. It doesn't even know any `compilerOptions` about `esModuleInterop`.

And it's not `regression` in my opinion then, it's just the correct behavior. Of course, it could be better to support `esModuleInterop` for `eslint-plugin-import`, and there is nothing we can do on side of `eslint-import-resolver-typescript`.

**Comment by joaovieira** [comment]
@JounQin I don't know how you can maintain this project with that attitude. I'm trying to help as you've seen. I'm not saying the problem is in the resolver - I already understood it isn't after having to dig in myself. But all these issues are related to the change in the way the resolver resolves files. You can't expect the rest of the ecosystem to automatically fix itself and just ignore it.

I've already understood the issue, so I'll move away from this thread as its not helpful.

**Comment by JounQin** [comment]
It is very clear I've answered your latest question at my first comment. It's great to address an issue or even usage question for this project, but I can't understand why I should answer same question for several tomes.

And also, I'm not ignoring them, I've answered every comment about this and pinned the most related two issues. If you'd like to help, you can also raise a PR mentioned about this.

**Comment by JounQin** [comment]
And also, we do have a [CHANGELOG](https://github.com/alexgorbatchev/eslint-import-resolver-typescript/blob/master/CHANGELOG.md) since `v2.0.0`, it's a BREAKING CHANGE, that's why we bump the major version.
