### ISSUE TITLE
npm package maintenance issue

### ISSUE THREAD

**Issue by JounQin** [alexgorbatchev/eslint-import-resolver-typescript#52]
Hi @alexgorbatchev @bradzacher 
Although I'm one of the GitHub collaborator of this project, but I'm not a publisher of its npm package, so even I can merge PRs, but I can't help to release a patch version into npm.

Would you like to help with this situation?

**Comment by bradzacher** [comment]
we had talked at one point about merging this tooling into the typescript-eslint project.
IIRC it didn't happen there was some pain due to timezones and syncing up and the fact that you can't just transfer a repo into an org very easily.

merging that in would make this easier to manage, as we could wrap up the release as part of that project's automated weekly releases.

---

What are the steps required to do a release? I'm happy to publish the latest master.

**Comment by alexgorbatchev** [comment]
@JounQin what is your NPM username?

**Comment by JounQin** [comment]
@alexgorbatchev My npm name is `jounqin`.

@bradzacher It would be great to merge.

**Comment by alexgorbatchev** [comment]
done

**Comment by alexgorbatchev** [comment]
@JounQin I dont see any PRs open?

**Comment by JounQin** [comment]
@alexgorbatchev Yes, merged but not published yet.
